const preload = `key	name	type	elt_1	elt_2	elt_3	elt_4	elt_5	elt_6	elt_7	elt_8	elt_9	elt_10	elt_11	elt_12	elt_13
															
pages	Pages	id	1	2	3	4	5	6	7	8	9	10	11	12	13
publish	Afficher dans le format	boolean	true	true	TRUE	true	TRUE	TRUE	TRUE	TRUE	TRUE	TRUE	TRUE	TRUE	TRUE
type	Type de slide	text	une	left	right	left	inter	left	right	inter	left	right	inter	left	right
title	Titre de la slide	html	"<span>AU NOM</span>
<span>DE LA LOI</span>"	"BABACAR<br />
GUEYE"	"SHAOYAO<br />
LIU"	"ALLAN<br />
LAMBIN"	"«&nbsp;EN FRANCE, LA POLICE A DES LBD ET DES
FUSILS..."	"MEHDI<br />
FARGHDANI"	"AMADOU<br />
KOUME"	ENTRE CRIMINALISATION ET NÉCESSITÉ D’INFORMER…	"WISSAM<br />
EL YAMNI"	"CLAUDE<br />
JEAN&#8209;PIERRE"	"«&nbsp;JE SAIS QUAND
ON ESSAIE DE ME LA
FAIRE À L’ENVERS&nbsp;»"	"OLIVIO<br />
GOMES"	"MOHAMED<br />
GABSI"
text	Texte de la slide	html	Derrière ces noms, il y avait des vies, celles de femmes et d’hommes tués au cours d’une intervention policière. «&nbsp;Le&nbsp;Monde&nbsp;» a choisi de replonger dans ces dossiers controversés en se basant sur les faits, les témoignages des proches et les éléments de l’enquête. Avec, d’un côté, des policiers qui assurent avoir agi dans le cadre de la loi et, de l’autre, des familles qui demandent justice, au nom de cette même loi.	Le combat d’Awa pour son frère&nbsp;: «&nbsp;La moindre des choses, quand la police tue quelqu’un, c’est d’avoir une vraie enquête et un procès.&nbsp;»	Trois enfants dans l’incompréhension&nbsp;: «&nbsp;Nous sommes les victimes et notre père ne méritait pas de mourir.&nbsp;»	Son père Franck attend toujours des réponses&nbsp;: «&nbsp;Le dernier combat qu’il me reste à mener, c’est de montrer que ces gens-là aussi peuvent être punis.&nbsp;»	"Un policier allemand
a seulement un pistolet
9mm&nbsp;»"	Sa mère Christine dénonce une bavure&nbsp;: «&nbsp;Si Mehdi est mort ce jour-là, c’est que le système a totalement dysfonctionné.&nbsp;»	Jessica Lefèvre, une compagne combative et dévouée&nbsp;: «&nbsp;Le droit est devenu une passion parce que c’était ma seule arme.&nbsp;»	L’enjeu de la médiatisation des profils des victimes	Sa mère Zohra en quête de vérité&nbsp;: «&nbsp;On attend de nous qu’on soit invisibles, qu’on se taise.&nbsp;»	A la Guadeloupe, l’indignation de toute une île&nbsp;: «&nbsp;Ils l’ont laissé comme mort sur le bitume brûlant, ils ne lui ont prodigué aucun premier soin.&nbsp;»	Cinq enquêteurs de l’IGPN racontent leur quotidien	Son frère Leonel compte sur la justice&nbsp;: «&nbsp;Aujourd’hui, j’ai toutes les réponses. Et j’attends que la peine du policier soit exemplaire.&nbsp;»	Ses proches comptent sur un procès&nbsp;: «&nbsp;Mohamed était malade. Au lieu d’avoir affaire à des professionnels de santé, il a eu affaire à des cow-boys.&nbsp;»
side_text	Texte de support de la slide	html	"IBRAHIMA BAH<br />
SHAOYAO LIU<br />
WISSAM EL-YAMNI<br />
BABACAR GUEYE<br />
ANGELO GARAND..."												
main_image_url	URL de l'image de premier plan	text		https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/BABACAR_GUEYE_APPEL.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/SHAOYAO_LIU_APPEL.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/AlLAN_LAMBIN_APPEL.jpg		https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/MEHDI_FARGHDANI_APPEL.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/AMADOU_KOUME_APPEL.jpg		https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/WISSAM_EL_YAMNI_APPEL.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/CLAUDE_JEAN-PIERRE_APPEL.jpg		https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/OLIVIO_GOMEZ_APPEL.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/MOHAMED_GABSI_APPEL.jpg
bg_image_url	URL de l'image de fond	text	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/OUVERTURE_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/BABACAR_GUEYE_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/SHAOYAO_LIU_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/ALLAN_LAMBIN_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/EUROPE_THEMA_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/MEHDI_FARGHDANI_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/AMADOU_KOUME_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/PROFILS_THEMA_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/WISSAM_EL_YAMNI_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/CLAUDE_JEAN-PIERRE_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/IGPN_THEMA_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/OLIVIO_GOMEZ_BG.jpg	https://assets-decodeurs.lemonde.fr/redacweb/3-2108-police/MOHAMED_GABSI_BG.jpg
link_url	URL du lien vers l'enquête	text		https://www.lemonde.fr/societe/article/2020/11/12/la-moindre-des-choses-quand-la-police-tue-quelqu-un-c-est-d-avoir-une-vraie-enquete-et-un-proces-le-combat-d-awa-gueye-pour-son-frere-babacar_6059514_3224.html	https://www.lemonde.fr/societe/article/2020/11/17/on-ne-comprenait-pas-ce-qu-il-se-passait-le-soir-ou-shaoyao-liu-a-ete-tue-par-la-police-devant-ses-enfants_6059996_3224.html	https://www.lemonde.fr/societe/article/2020/12/18/violences-policieres-pres-de-deux-ans-apres-la-mort-d-allan-lambin-en-garde-a-vue-ses-proches-toujours-en-quete-de-reponses_6063813_3224.html	https://www.lemonde.fr/societe/article/2020/11/17/en-europe-du-nord-les-policiers-apprennent-a-rechercher-l-apaisement-plus-qu-a-s-imposer-y-compris-dans-une-situation-stressante_6060044_3224.html	https://www.lemonde.fr/societe/article/2021/07/01/mehdi-farghdani-une-crise-de-paranoia-et-six-balles-dans-le-corps_6086486_3224.html	https://www.lemonde.fr/societe/article/2021/02/16/violences-policieres-six-ans-apres-la-mort-d-amadou-koume-le-combat-de-sa-compagne-pour-reclamer-justice_6070155_3224.html	https://www.lemonde.fr/societe/article/2021/07/06/entre-criminalisation-et-necessite-d-informer-l-elaboration-du-profil-des-personnes-mortes-lors-d-interventions-policieres_6087117_3224.html	https://www.lemonde.fr/police-justice/article/2020/07/15/huit-ans-apres-la-mort-de-wissam-el-yamni-des-suites-de-son-interpellation-le-combat-d-une-famille-pour-la-verite_6046203_1653578.html	https://www.lemonde.fr/societe/article/2021/05/20/guadeloupe-claude-jean-pierre-visage-de-la-lutte-contre-les-brutalites-policieres_6080806_3224.html	https://www.lemonde.fr/societe/article/2021/08/06/je-sais-quand-un-collegue-essaie-de-me-la-faire-a-l-envers-cinq-enqueteurs-de-l-igpn-racontent-leur-quotidien_6090671_3224.html	https://www.lemonde.fr/societe/article/2021/05/13/les-incoherences-autour-de-la-mort-d-olivio-gomes-tue-par-la-police-au-terme-d-une-filature_6080057_3224.html	https://www.lemonde.fr/societe/article/2020/12/18/a-l-aide-ils-veulent-me-tuer-les-dernieres-minutes-de-mohamed-gabsi-mort-en-avril-apres-une-interpellation-policiere-a-beziers_6063902_3224.html
`

export default preload